# Generated by Django 5.0.2 on 2024-03-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userdata_password_reset_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='password_reset_token_expire',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='password_reset_token_generated_time',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='password_reset_token_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='password_reset_token_generated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
